---
satellite:
  version: "6.10" 
  admin_username: admin
  admin_password: changemeafterinstalled
  tuning_config_files:
    - name: dynflowd.j2
      path: /etc/sysconfig/dynflowd
    - name: httpd_limits.conf.j2
      path: /etc/systemd/system/httpd.service.d/limits.conf
    - name: 01-satellite-tune.conf.j2
      path: /etc/sysctl.d/01-satellite-tune.conf
  foreman:
    organizations:
      - name: AWS
        initial_organization: true
    locations:
      - name: us-west
        initial_location: true
        organizations:
          - name: AWS

