---

- name: Fail if no Red Hat Subscription Manager authentication data is passed to the role
  fail: msg="You must pass authentication data to this role. See README.md"
  when: "( rhn_user is not defined or rhn_pass is not defined ) and rhn_activation_key is not defined and rhn_pool_ids is not defined" 

- name: Confirm DNS resoultion for short domain name of this host
  shell: "ping -c1 $(hostname -s)"
  changed_when: False

- name: Confirm DNS resolution for fully-qualified domain name of this host
  shell: "ping -c1 $(hostname -f)"
  changed_when: False

- name: Enable RHEL subscription via username/password
  community.general.redhat_subscription: 
    state: present 
    username: "{{ rhn_user }}"
    password: "{{ rhn_pass }}"
    pool: ".*Red Hat (Enterprise Linux|Satellite).*"
  when: rhn_user is defined and rhn_pass is defined

- name: Enable RHEL subscription via activation key
  community.general.redhat_subscription: 
    state: present 
    activationkey: "{{ rhn_activationkey }}"
    pool: ".*Red Hat (Enterprise Linux|Satellite).*"
  when: rhn_activation_key is defined

- name: Configure Repositories
  ansible.builtin.import_tasks: configure-repositories.yml

- name: Remove conflicting RPMs
  ansible.builtin.import_tasks: remove-conflicting-rpms.yml

- name: Install RPMs
  ansible.builtin.import_tasks: install-satellite-rpms.yml

- name: Import Firewall Tasks
  ansible.builtin.import_tasks: firewall.yml

- name: Set Satellite Master Install Settings
  ansible.builtin.include_tasks: set-initial-install-settings.yml
  # My use case will only be Satellite
  #  when:
  #    - "'satellite' in group_names"

- name: Import Satellite Install Tasks
  ansible.builtin.include_tasks: run-satellite-installer.yml

  # My use case will only be Satellite.  If using capsules, uncomment
      #- name: Import Capsule Install Tasks
      #  ansible.builtin.include_tasks: capsule.yml
      #  when:
      #    - "'capsule' in group_names"
